package com.mygdx.eoh.enums;

/**
 * Animation types.
 * Created by v on 2016-10-19.
 */
public enum AnimationTypes {
    ApBarAnimation,
    ManaBarAnimation,
    CastleAnimation,
    CastleSelectedAnimation,
    HospitalAnimation,
    //KnightAnimation,
    KnightCast,
    KnightStanding,
    KnightSelected,
    ArrowMoveN,
    ArrowMoveS,
    ArrowMoveW,
    ArrowMoveE,
    ArrowMoveNE,
    ArrowMoveNW,
    ArrowMoveSW,
    ArrowMoveSE,
    CancelMove,
    AttackMove,
    CastMove,
    KnightWalkN,
    KnightWalkS,
    KnightWalkE,
    KnightWalkW,
    KnightAttackS,
    KnightAttackW,
    KnightAttackN,
    KnightAttackE,
    WizardStanding,
    WizardSelected,
    WizardWalkN,
    WizardWalkS,
    WizardWalkE,
    WizardWalkW,
    WizardAttackN,
    WizardAttackS,
    WizardAttackE,
    WizardAttackW,
    ItemGold,
    HealthPotionAnimation,
    ManaPotionAnimation,
    PotionUseAnimation
}
